## YAML Template.
s4tabitay\VitrineBundle\Entity\Client:       # L’espace de nom où sera créée l’entité
    type: entity
    table: client                        # La table a laquelle elle correspond
    id:                                   # Les champs qui composent la clé primaire
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:                               # Les autres champs de la table
        nom:
            type: string
            length: 100
        adressemail:
            type: string
            legth: 100
    oneToMany:                        # Dans l’entité Category on ajoute un champ
        commande:                     # products qui permet d’associer à une Category
            targetEntity: Commande    # toutes les entités Products dont le champ
            mappedBy: client       # category pointe vers cette entité.
