s4tabitay_vitrine_homepage:
    path: /accueil/{name}
    defaults: { _controller: s4tabitayVitrineBundle:Default:index,name: Visiteur }

s4tabitay_vitrine_mentions:
    path: /mentions
    defaults: { _controller: s4tabitayVitrineBundle:Default:mentions }
    
s4tabitay_vitrine_catalogue:
    path: /catalogue
    defaults: { _controller: s4tabitayVitrineBundle:Default:catalogue }
    
s4tabitay_vitrine_articleParCategorie:
    path: /ArticleParCategorie/{cat}
    defaults: { _controller: s4tabitayVitrineBundle:Default:articleParCategorie }
    
s4tabitay_vitrine_panier:
    path: /contenuPanier/
    defaults: { _controller: s4tabitayVitrineBundle:Panier:contenuPanier }
    
s4tabitay_vitrine_addArticle:
    path: /ajouterArticle/{id}/
    defaults: { _controller: s4tabitayVitrineBundle:Panier:ajouterUnArticle, quantity: 1 }

s4tabitay_vitrine_addArticles:
    path: /ajouterArticles/{id}/{quantity}
    defaults: { _controller: s4tabitayVitrineBundle:Panier:ajouterArticles, quantity: 1 }

s4tabitay_vitrine_empty:
    path: /viderPanier/
    defaults: { _controller: s4tabitayVitrineBundle:Panier:viderPanier}
